
const validGames = [
    { type: "7d2d", name: "7 Days to Die (2013)" },
    { type: "ageofchivalry", name: "Age of Chivalry (2007)" },
    { type: "aoe2", name: "Age of Empires 2 (1999)" },
    { type: "alienarena", name: "Alien Arena (2004)" },
    { type: "alienswarm", name: "Alien Swarm (2010)" },
    { type: "arkse", name: "Ark: Survival Evolved (2017)" },
    { type: "assettocorsa", name: "Assetto Corsa (2014)" },
    { type: "atlas", name: "Atlas (2018)" },
    { type: "avp2", name: "Aliens versus Predator 2 (2001)" },
    { type: "avp2010", name: "Aliens vs. Predator (2010)" },
    { type: "americasarmy", name: "America's Army (2002)" },
    { type: "americasarmy2", name: "America's Army 2 (2003)" },
    { type: "americasarmy3", name: "America's Army 3 (2009)" },
    { type: "americasarmypg", name: "America's Army: Proving Grounds (2015)" },
    { type: "arcasimracing", name: "Arca Sim Racing (2008)" },
    { type: "arma", name: "ARMA: Armed Assault (2007)" },
    { type: "arma2", name: "ARMA 2 (2009)" },
    { type: "arma2oa", name: "ARMA 2: Operation Arrowhead (2010)" },
    { type: "armacwa", name: "ARMA: Cold War Assault (2011)" },
    { type: "armar", name: "ARMA: Resistance (2011)" },
    { type: "arma3", name: "ARMA 3 (2013)" },
    { type: "armagetron", name: "Armagetron Advanced (2001)" },
    { type: "baldursgate", name: "Baldur's Gate (1998)" },
    { type: "barotrauma", name: "Barotrauma (2019)" },
    { type: "bat1944", name: "Battalion 1944 (2018)" },
    { type: "bf1942", name: "Battlefield 1942 (2002)" },
    { type: "bfv", name: "Battlefield Vietnam (2004)" },
    { type: "bf2", name: "Battlefield 2 (2005)" },
    { type: "bf2142", name: "Battlefield 2142 (2006)" },
    { type: "bfbc2", name: "Battlefield: Bad Company 2 (2010)" },
    { type: "bf3", name: "Battlefield 3 (2011)" },
    { type: "bf4", name: "Battlefield 4 (2013)" },
    { type: "bfh", name: "Battlefield Hardline (2015)" },
    { type: "breach", name: "Breach (2011)" },
    { type: "breed", name: "Breed (2004)" },
    { type: "brink", name: "Brink (2011)" },
    { type: "buildandshoot", name: "Build and Shoot / Ace of Spades Classic (2012)" },
    { type: "cod", name: "Call of Duty (2003)" },
    { type: "coduo", name: "Call of Duty: United Offensive (2004)" },
    { type: "cod2", name: "Call of Duty 2 (2005)" },
    { type: "cod3", name: "Call of Duty 3 (2006)" },
    { type: "cod4", name: "Call of Duty 4: Modern Warfare (2007)" },
    { type: "codwaw", name: "Call of Duty: World at War (2008)" },
    { type: "codmw2", name: "Call of Duty: Modern Warfare 2 (2009)" },
    { type: "codmw3", name: "Call of Duty: Modern Warfare 3 (2011)" },
    { type: "callofjuarez", name: "Call of Juarez (2006)" },
    { type: "chaser", name: "Chaser (2003)" },
    { type: "chrome", name: "Chrome (2003)" },
    { type: "codenameeagle", name: "Codename Eagle (2000)" },
    { type: "commandos3", name: "Commandos 3: Destination Berlin (2003)" },
    { type: "cacrenegade", name: "Command and Conquer: Renegade (2002)" },
    { type: "conanexiles", name: "Conan Exiles (2018)" },
    { type: "contagion", name: "Contagion (2011)" },
    { type: "contactjack", name: "Contract J.A.C.K. (2003)" },
    { type: "cs15", name: "Counter-Strike 1.5 (2002)" },
    { type: "cs16", name: "Counter-Strike 1.6 (2003)" },
    { type: "cs2d", name: "Counter-Strike: 2D (2004)" },
    { type: "cscz", name: "Counter-Strike: Condition Zero (2004)" },
    { type: "css", name: "Counter-Strike: Source (2004)" },
    { type: "csgo", name: "Counter-Strike: Global Offensive (2012)" },
    { type: "crossracing", name: "Cross Racing Championship Extreme 2005 (2005)" },
    { type: "crysis", name: "Crysis (2007)" },
    { type: "crysiswars", name: "Crysis Wars (2008)" },
    { type: "crysis2", name: "Crysis 2 (2011)" },
    { type: "daikatana", name: "Daikatana (2000)" },
    { type: "dmomam", name: "Dark Messiah of Might and Magic (2006)" },
    { type: "darkesthour", name: "Darkest Hour: Europe '44-'45 (2008)" },
    { type: "daysofwar", name: "Days of War (2017)" },
    { type: "dayz", name: "DayZ (2018)" },
    { type: "dayzmod", name: "DayZ Mod (2013)" },
    { type: "deadlydozenpt", name: "Deadly Dozen: Pacific Theater (2002)" },
    { type: "dh2005", name: "Deer Hunter 2005 (2004)" },
    { type: "descent3", name: "Descent 3 (1999)" },
    { type: "deusex", name: "Deus Ex (2000)" },
    { type: "devastation", name: "Devastation (2003)" },
    { type: "dinodday", name: "Dino D-Day (2011)" },
    { type: "dirttrackracing2", name: "Dirt Track Racing 2 (2002)" },
    { type: "discord", name: "Discord" },
    { type: "dnl", name: "Dark and Light (2017)" },
    { type: "dod", name: "Day of Defeat (2003)" },
    { type: "dods", name: "Day of Defeat: Source (2005)" },
    { type: "doi", name: "Day of Infamy (2017)" },
    { type: "doom3", name: "Doom 3 (2004)" },
    { type: "dota2", name: "Dota 2 (2013)" },
    { type: "drakan", name: "Drakan: Order of the Flame (1999)" },
    { type: "empyrion", name: "Empyrion - Galactic Survival (2015)" },
    { type: "etqw", name: "Enemy Territory: Quake Wars (2007)" },
    { type: "fear", name: "F.E.A.R. (2005)" },
    { type: "f12002", name: "Formula One 2002 (2002)" },
    { type: "f1c9902", name: "F1 Challenge '99-'02 (2002)" },
    { type: "farcry", name: "Far Cry (2004)" },
    { type: "farcry2", name: "Far Cry 2 (2008)" },
    { type: "fortressforever", name: "Fortress Forever (2007)" },
    { type: "operationflashpoint,flashpoint", name: "Operation Flashpoint: Cold War Crisis (2001)" },
    { type: "flashpointresistance", name: "Operation Flashpoint: Resistance (2002)" },
    { type: "ffow", name: "Frontlines: Fuel of War (2008)" },
    { type: "fivem", name: "Grand Theft Auto V - FiveM (2013)" },
    { type: "forrest", name: "The Forrest (2014)" },
    { type: "garrysmod", name: "Garry's Mod (2004)" },
    { type: "graw", name: "Tom Clancy's Ghost Recon Advanced Warfighter (2006)" },
    { type: "graw2", name: "Tom Clancy's Ghost Recon Advanced Warfighter 2 (2007)" },
    { type: "giantscitizenkabuto", name: "Giants: Citizen Kabuto (2000)" },
    { type: "globaloperations", name: "Global Operations (2002)" },
    { type: "geneshift,mutantfactions", name: "Geneshift (2017)" },
    { type: "ges", name: "GoldenEye: Source (2010)" },
    { type: "gore", name: "Gore: Ultimate Soldier (2002)" },
    { type: "groundbreach", name: "Ground Breach (2018)" },
    { type: "gunmanchronicles", name: "Gunman Chronicles (2000)" },
    { type: "hldm", name: "Half-Life Deathmatch (1998)" },
    { type: "hldms", name: "Half-Life Deathmatch: Source (2005)" },
    { type: "hl2dm", name: "Half-Life 2: Deathmatch (2004)" },
    { type: "halo", name: "Halo (2003)" },
    { type: "halo2", name: "Halo 2 (2007)" },
    { type: "heretic2", name: "Heretic II (1998)" },
    { type: "hexen2", name: "Hexen II (1997)" },
    { type: "hidden", name: "The Hidden (2005)" },
    { type: "hll", name: "Hell Let Loose" },
    { type: "had2", name: "Hidden & Dangerous 2 (2003)" },
    { type: "homefront", name: "Homefront (2011)" },
    { type: "homeworld2", name: "Homeworld 2 (2003)" },
    { type: "hurtworld", name: "Hurtworld (2015)" },
    { type: "igi2", name: "I.G.I.-2: Covert Strike (2003)" },
    { type: "il2", name: "IL-2 Sturmovik (2001)" },
    { type: "insurgency", name: "Insurgency (2014)" },
    { type: "insurgencysandstorm", name: "Insurgency: Sandstorm (2018)" },
    { type: "ironstorm", name: "Iron Storm (2002)" },
    { type: "jamesbondnightfire", name: "James Bond 007: Nightfire (2002)" },
    { type: "jc2mp", name: "Just Cause 2 - Multiplayer (2010)" },
    { type: "jc3mp", name: "Just Cause 3 - Multiplayer (2017)" },
    { type: "killingfloor", name: "Killing Floor (2009)" },
    { type: "killingfloor2", name: "Killing Floor 2 (2016)" },
    { type: "kingpin", name: "Kingpin: Life of Crime (1999)" },
    { type: "kisspc", name: "Kiss: Psycho Circus: The Nightmare Child (2000)" },
    { type: "kspdmp", name: "Kerbal Space Program - DMP Multiplayer (2015)" },
    { type: "kzmod", name: "Kreedz Climbing (2017)" },
    { type: "left4dead", name: "Left 4 Dead (2008)" },
    { type: "left4dead2", name: "Left 4 Dead 2 (2009)" },
    { type: "m2mp", name: "Mafia II - Multiplayer (2010)" },
    { type: "m2o", name: "Mafia II - Online (2010)" },
    { type: "medievalengineers", name: "Medieval Engineers (2015)" },
    { type: "mohaa", name: "Medal of Honor: Allied Assault (2002)" },
    { type: "mohsh", name: "Medal of Honor: Allied Assault Spearhead (2002)" },
    { type: "mohbt", name: "Medal of Honor: Allied Assault Breakthrough (2003)" },
    { type: "mohpa", name: "Medal of Honor: Pacific Assault (2004)" },
    { type: "mohab", name: "Medal of Honor: Airborne (2007)" },
    { type: "moh2010", name: "Medal of Honor (2010)" },
    { type: "mohwf", name: "Medal of Honor: Warfighter (2012)" },
    { type: "minecraft", name: "Minecraft (2009)" },
    { type: "minecraftbe", name: "Minecraft: Bedrock Edition (2011)" },
    { type: "mnc", name: "Monday Night Combat (2011)" },
    { type: "mordhau", name: "Mordhau (2019)" },
    { type: "mtavc", name: "Grand Theft Auto: Vice City - Multi Theft Auto (2002)" },
    { type: "mtasa", name: "Grand Theft Auto: San Andreas - Multi Theft Auto (2004)" },
    { type: "mumble", name: "Mumble - GTmurmur Plugin (2005)" },
    { type: "mumbleping", name: "Mumble - Lightweight (2005)" },
    { type: "nascarthunder2004", name: "NASCAR Thunder 2004 (2003)" },
    { type: "netpanzer", name: "netPanzer (2002)" },
    { type: "nmrih", name: "No More Room in Hell (2011)" },
    { type: "ns", name: "Natural Selection (2002)" },
    { type: "ns2", name: "Natural Selection 2 (2012)" },
    { type: "nfshp2", name: "Need for Speed: Hot Pursuit 2 (2002)" },
    { type: "nab", name: "Nerf Arena Blast (1999)" },
    { type: "nwn", name: "Neverwinter Nights (2002)" },
    { type: "nwn2", name: "Neverwinter Nights 2 (2006)" },
    { type: "nexuiz", name: "Nexuiz (2005)" },
    { type: "nitrofamily", name: "Nitro Family (2004)" },
    { type: "nolf", name: "The Operative: No One Lives Forever (2000)" },
    { type: "nolf2", name: "No One Lives Forever 2: A Spy in H.A.R.M.'s Way (2002)" },
    { type: "nucleardawn", name: "Nuclear Dawn (2011)" },
    { type: "openarena", name: "OpenArena (2005)" },
    { type: "openttd", name: "OpenTTD (2004)" },
    { type: "painkiller", name: "Painkiller" },
    { type: "pixark", name: "PixARK (2018)" },
    { type: "ps", name: "Post Scriptum" },
    { type: "postal2", name: "Postal 2" },
    { type: "prey", name: "Prey" },
    { type: "primalcarnage", name: "Primal Carnage: Extinction" },
    { type: "prbf2", name: "Project Reality: Battlefield 2 (2005)" },
    { type: "przomboid", name: "Project Zomboid" },
    { type: "quake1", name: "Quake 1: QuakeWorld (1996)" },
    { type: "quake2", name: "Quake 2 (1997)" },
    { type: "quake3", name: "Quake 3: Arena (1999)" },
    { type: "quake4", name: "Quake 4 (2005)" },
    { type: "quakelive", name: "Quake Live (2010)" },
    { type: "ragdollkungfu", name: "Rag Doll Kung Fu" },
    { type: "r6", name: "Rainbow Six" },
    { type: "r6roguespear", name: "Rainbow Six 2: Rogue Spear" },
    { type: "r6ravenshield", name: "Rainbow Six 3: Raven Shield" },
    { type: "rallisportchallenge", name: "RalliSport Challenge" },
    { type: "rallymasters", name: "Rally Masters" },
    { type: "redorchestra", name: "Red Orchestra" },
    { type: "redorchestraost", name: "Red Orchestra: Ostfront 41-45" },
    { type: "redorchestra2", name: "Red Orchestra 2" },
    { type: "redline", name: "Redline" },
    { type: "rtcw", name: "Return to Castle Wolfenstein" },
    { type: "rfactor", name: "rFactor" },
    { type: "ricochet", name: "Ricochet" },
    { type: "riseofnations", name: "Rise of Nations" },
    { type: "rs2", name: "Rising Storm 2: Vietnam" },
    { type: "rune", name: "Rune" },
    { type: "rust", name: "Rust" },
    { type: "samp", name: "San Andreas Multiplayer" },
    { type: "savage2", name: "Savage 2: A Tortured Soul (2008)" },
    { type: "spaceengineers", name: "Space Engineers" },
    { type: "ss", name: "Serious Sam" },
    { type: "ss2", name: "Serious Sam 2" },
    { type: "shatteredhorizon", name: "Shattered Horizon" },
    { type: "ship", name: "The Ship" },
    { type: "shogo", name: "Shogo" },
    { type: "shootmania", name: "Shootmania" },
    { type: "sin", name: "SiN" },
    { type: "sinep", name: "SiN Episodes" },
    { type: "soldat", name: "Soldat" },
    { type: "sof", name: "Soldier of Fortune" },
    { type: "sof2", name: "Soldier of Fortune 2" },
    { type: "stalker", name: "S.T.A.L.K.E.R." },
    { type: "stbc", name: "Star Trek: Bridge Commander" },
    { type: "stvef", name: "Star Trek: Voyager - Elite Force" },
    { type: "stvef2", name: "Star Trek: Voyager - Elite Force 2" },
    { type: "squad", name: "Squad" },
    { type: "swbf", name: "Star Wars: Battlefront" },
    { type: "swbf2", name: "Star Wars: Battlefront 2" },
    { type: "swjk", name: "Star Wars Jedi Knight: Jedi Academy (2003)" },
    { type: "swjk2", name: "Star Wars Jedi Knight II: Jedi Outcast (2002)" },
    { type: "swrc", name: "Star Wars: Republic Commando" },
    { type: "starbound", name: "Starbound" },
    { type: "starmade", name: "StarMade" },
    { type: "starsiege", name: "Starsiege (2009)" },
    { type: "suicidesurvival", name: "Suicide Survival" },
    { type: "swat4", name: "SWAT 4" },
    { type: "svencoop", name: "Sven Coop" },
    { type: "synergy", name: "Synergy" },
    { type: "tacticalops", name: "Tactical Ops" },
    { type: "takeonhelicopters", name: "Take On Helicopters (2011)" },
    { type: "teamfactor", name: "Team Factor" },
    { type: "tfc", name: "Team Fortress Classic" },
    { type: "tf2", name: "Team Fortress 2" },
    { type: "teamspeak2", name: "Teamspeak 2" },
    { type: "teamspeak3", name: "Teamspeak 3" },
    { type: "terminus", name: "Terminus" },
    { type: "terraria,tshock", name: "Terraria - TShock (2011)" },
    { type: "thps3", name: "Tony Hawk's Pro Skater 3" },
    { type: "thps4", name: "Tony Hawk's Pro Skater 4" },
    { type: "thu2", name: "Tony Hawk's Underground 2" },
    { type: "towerunite", name: "Tower Unite" },
    { type: "trackmania2", name: "Trackmania 2" },
    { type: "trackmaniaforever", name: "Trackmania Forever" },
    { type: "tremulous", name: "Tremulous" },
    { type: "tribes1", name: "Tribes 1: Starsiege" },
    { type: "tribesvengeance", name: "Tribes: Vengeance" },
    { type: "tron20", name: "Tron 2.0" },
    { type: "turok2", name: "Turok 2" },
    { type: "universalcombat", name: "Universal Combat" },
    { type: "unreal", name: "Unreal" },
    { type: "unturned", name: "unturned" },
    { type: "ut", name: "Unreal Tournament" },
    { type: "ut2003", name: "Unreal Tournament 2003" },
    { type: "ut2004", name: "Unreal Tournament 2004" },
    { type: "ut3", name: "Unreal Tournament 3" },
    { type: "urbanterror", name: "Urban Terror" },
    { type: "v8supercar", name: "V8 Supercar Challenge" },
    { type: "valheim", name: "Valheim (2021)" },
    { type: "vcmp", name: "Vice City Multiplayer" },
    { type: "ventrilo", name: "Ventrilo" },
    { type: "vietcong", name: "Vietcong" },
    { type: "vietcong2", name: "Vietcong 2" },
    { type: "warsow", name: "Warsow" },
    { type: "wheeloftime", name: "Wheel of Time" },
    { type: "wolfenstein2009", name: "Wolfenstein 2009" },
    { type: "wolfensteinet", name: "Wolfenstein: Enemy Territory" },
    { type: "xpandrally", name: "Xpand Rally" },
    { type: "zombiemaster", name: "Zombie Master" },
    { type: "zps", name: "Zombie Panic: Source" }
]

export default validGames