version: '3.5'

services:
  gssc:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      network: backend

    networks:
      - web
      - backend
    container_name: gssc-next
    restart: always
    dns:
      - 1.1.1.1
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/gssc?schema=public
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  web:
    external: true
  backend:
    name: backend

volumes:
  postgresdata:
