version: '3'

services:
  gssc:
    build: .
    networks:
      - web
    container_name: gssc-next
    dns:
      - 1.1.1.1
  # db:
  #   image: postgres:alpine
  #   restart: always
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./postgresdata:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  # db-admin:
  #   image: michalhosna/adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - ./.env
  #   environment:
  #     ADMINER_DB: "${POSTGRES_DB}"
  #     ADMINER_DRIVER: pgsql
  #     ADMINER_PASSWORD: "${POSTGRES_PASSWORD}"
  #     ADMINER_SERVER: db
  #     ADMINER_USERNAME: ${POSTGRES_USER}
  #     ADMINER_AUTOLOGIN: 1
  #     ADMINER_NAME: DB admin
  #   depends_on:
  #     - db

networks:
  web:
    external: true
