version: '3'

services:
  next:
    build: .
    container_name: gssc-next
    networks:
      - web
    dns:
      - 192.168.50.238
      - 192.168.50.230
      - 8.8.8.8

networks:
  web:
    external: true